name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.5
      with:
        github_repo_id: 'tooget/DataAnalysis-MachineLearning-Template'
        huggingface_repo_id: 'tooget/DataAnalysis-MachineLearning-Template'
        repo_type: 'space'
        space_sdk: 'streamlit'
        hf_token: ${{ secrets.HF_TOOGET_TOKEN_FOR_GITHUB_SYNC }}
